### ISSUE TITLE
MVP: Devlake should be automatically configured with Backstage Resources

### ISSUE THREAD

**Issue by brunocribeiro** [DevoteamNL/opendora#67]
Goal: have a way of automatically setting up Apache Devlake so that users of the OpenDORA Backstage Plugin don't need to interact with it directly

Value: as a Backstage setup could have hundreds of components, it's not feasible to set up Devlake manually in some use cases. For that reason, an automatic way of discovering and setting up Backstage components is needed. That will simplify the use of the OpenDORA Backstage plugin

Deliverables:

- [ ] Devlake's configuration is automatically created/updated according to Backstage's catalogue
- [ ] OpenDORA plugin is configurable per component (disabled by default, flexible project matching)

```[tasklist]
### Tasks
- [ ] https://github.com/DevoteamNL/opendora/issues/59
- [ ] https://github.com/DevoteamNL/opendora/issues/64
- [ ] https://github.com/DevoteamNL/opendora/issues/65
- [ ] https://github.com/DevoteamNL/opendora/issues/66
```
