### ISSUE TITLE
MVP: Refactoring and Improvements

### ISSUE THREAD

**Issue by brunocribeiro** [DevoteamNL/opendora#71]
Goal: ...

Value: ...

Deliverables:

- [ ] Have test suites for every component of the solution
- [ ] Support other filters in the plugin (time window, team/group)

```[tasklist]
### Tasks
- [ ] https://github.com/DevoteamNL/opendora/issues/62
- [ ] https://github.com/DevoteamNL/opendora/issues/63
- [ ] https://github.com/DevoteamNL/opendora/issues/68
- [ ] https://github.com/DevoteamNL/opendora/issues/69
- [ ] https://github.com/DevoteamNL/opendora/issues/82
- [ ] https://github.com/DevoteamNL/opendora/issues/81
- [ ] https://github.com/DevoteamNL/opendora/issues/99
- [ ] https://github.com/DevoteamNL/opendora/issues/100
```
