### ISSUE TITLE
MVP: Lead time for changes DORA Metric

### ISSUE THREAD

**Issue by brunocribeiro** [DevoteamNL/opendora#72]
Goal: The OpenDORA plugin is also capable of showing the Lead time for changes DORA metric.

Value: as it's one of the 4 more important DORA metrics, it's a MUST-HAVE for the plugin

Deliverables: 

- [x] Backend to provide the Gitlab Deployment Datafields using the out-of-the-box Apache Devlake integration
- [x] The REST API endpoint is extended to support the `ltc_*` metric type and retrieve data for the frontend plugin
- [x] The Backstage FE plugin can plot a chart for the `Lead time for changes` metric

Assumptions:

- The end-user/operator will setup the necessary connections to GitLab and provide the necessary transformations (if the defaults don't suffice) for determining PR -> deployment relationships.
```[tasklist]
### Tasks
- [ ] https://github.com/DevoteamNL/opendora/issues/76
- [ ] https://github.com/DevoteamNL/opendora/issues/84
- [ ] https://github.com/DevoteamNL/opendora/issues/85
- [ ] https://github.com/DevoteamNL/opendora/issues/95
- [ ] https://github.com/DevoteamNL/opendora/issues/94
```
