### ISSUE TITLE
MVP: Deployment Frequency DORA Metric

### ISSUE THREAD

**Issue by mdkok02** [DevoteamNL/opendora#8]
Goal: Deliver a Backstage plugin that shows the deployment frequency on the Backstage kind Component level.

Value

Deliverables: 

- [x] Backend to provide the Gitlab Deployment Datafields using the out-of-the-box Apache Devlake integration
- [x] Import the Group kind from the backstage catalogue to serve as the team structure in the dev lake
- [x] REST API to provide the required data for the frontend plugin
- [x] Backstage FE plugin: Deployment Frequency Count Metric
- [x] Resources to simplify solution deployment (plugin's NPM package, API docker image and API + DevLake helm chart)
 
```[tasklist]
### Tasks
- [ ] https://github.com/DevoteamNL/opendora/issues/9
- [ ] https://github.com/DevoteamNL/opendora/issues/26
- [ ] https://github.com/DevoteamNL/opendora/issues/10
- [ ] https://github.com/DevoteamNL/opendora/issues/13
- [ ] https://github.com/DevoteamNL/opendora/issues/14
- [ ] https://github.com/DevoteamNL/opendora/issues/43
- [ ] https://github.com/DevoteamNL/opendora/issues/44
- [ ] https://github.com/DevoteamNL/opendora/issues/47
- [ ] https://github.com/DevoteamNL/opendora/issues/45
- [ ] https://github.com/DevoteamNL/opendora/issues/61
- [ ] https://github.com/DevoteamNL/opendora/issues/74
- [ ] https://github.com/DevoteamNL/opendora/issues/11
- [ ] https://github.com/DevoteamNL/opendora/issues/92
- [ ] https://github.com/DevoteamNL/opendora/issues/90
```
